SELECT YEAR(sales_date) as YEAR, MONTH(sales_date) as MONTH, gender as GENDER, COUNT(DISTINCT u.user_id) as USERS
FROM USER_INFO u
JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, u.GENDER
ORDER BY YEAR, MONTH, u.GENDER