SELECT u.USER_ID,
        u.NICKNAME, 
        CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) as 전체주소, 
        CONCAT_WS('-', SUBSTR(u.TLNO, 1, 3), SUBSTRING(u.TLNO, 4, 4), SUBSTRING(u.TLNO,8, 4)) as 전화번호
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u ON u.USER_ID = b.WRITER_ID
GROUP BY b.WRITER_ID HAVING COUNT(BOARD_ID) >= 3
ORDER BY USER_ID DESC