WITH t AS (
    SELECT *, SUM(TOTAL_ORDER) as JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR)

SELECT t.FLAVOR
FROM t
JOIN FIRST_HALF fh ON t.FLAVOR = fh.FLAVOR
GROUP BY t.FLAVOR
ORDER BY SUM (fh.TOTAL_ORDER + JULY_TOTAL_ORDER) DESC
LIMIT 3