SELECT USER_ID, NICKNAME, SUM(b.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u ON u.USER_ID = b.WRITER_ID
WHERE STATUS = "DONE" 
GROUP BY b.WRITER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC