
SELECT CATEGORY, SUM(total) as TOTAL_SALES
FROM BOOK B JOIN (
    SELECT BOOK_ID, SUM(SALES) as total
    FROM BOOK_SALES
    WHERE MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) S USING(BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY;