SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) as TOTAL_SALES
FROM BOOK_SALES s
JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC

# SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) as TOTAL_SALES
# FROM BOOK_SALES s
# JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
# JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
# WHERE SALES_DATE LIKE "2022-01%"
# GROUP BY b.AUTHOR_ID, b.CATEGORY
# ORDER BY a.AUTHOR_ID, b.CATEGORY DESC