SELECT t.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_TREE t
JOIN ITEM_INFO i ON i.ITEM_ID = t.ITEM_ID
WHERE t.PARENT_ITEM_ID IN (SELECT ITEM_ID
                            FROM ITEM_INFO
                            WHERE RARITY = 'RARE')
ORDER BY t.ITEM_ID DESC;