WITH VALUEBYYEAR AS (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
                    FROM ECOLI_DATA
                    GROUP BY YEAR)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, VALUEBYYEAR.MAX_SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV, ID 
FROM ECOLI_DATA
JOIN VALUEBYYEAR ON VALUEBYYEAR.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC
