SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
JOIN PATIENT p ON a.PT_NO = p.PT_NO
JOIN DOCTOR d ON d.DR_ID = a.MDDR_ID
WHERE a.MCDP_CD = 'CS' AND APNT_CNCL_YMD IS NULL AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD